### ISSUE TITLE
Potential for false negatives in docker tests

### ISSUE THREAD

**Issue by singlethink** [HewlettPackard/reconbf#8]
Many of the docker tests in [test_docker.py](https://github.com/viraptor/reconbf/blob/master/reconbf/modules/test_docker.py) have the potential to return false negatives if there is more than one docker process running on the system.  Many tests use the following pattern to examine the arguments given to the docker process:

```py
    for entry in docker_ps:
        if '--icc=false' in entry:
            result = TestResult(Result.PASS)
        else:
            reason = "Direct communication between containers is enabled."
            result = TestResult(Result.FAIL, reason)

    return result
```

If a failing process entry is followed by a process entry that passes, the failure will be suppressed.  These tests should probably return a `GroupTestResult` instead.

Caveat: This problem may affect non-docker tests too.  I haven't looked.

**Comment by viraptor** [comment]
Thanks for spotting that! I'll check it soon.

**Comment by viraptor** [comment]
I reviewed the docker tests that return a single result and found that they're actually checking options on the main dockerd process, not options for each container. While it's not wrong, there's quite a bit that could be improved though. That's issue #9 now.

**Comment by viraptor** [comment]
Yeah, that needs fixing in a few places. I misunderstood this entry initially, so there's a temporary issue 9, but actually this belongs here:

"""
Many docker tests browser the processes to find anything containing "docker", but actually they only require the main dockerd process(es).

A few possible improvements:

- get only the main process, not everything in the system (dockerd, possibly with PPID 0)
- cache the result
- get the precise PID from systemctl if possible instead of looking through /proc

"""

PS. What's the use case for running multiple dockerd processes? I wonder if that's a reason to add some more checks...

**Comment by viraptor** [comment]
Should be all fixed now. We still need to readd some tests that were too broken/questionable, but the rest works.
